create table test ( col1 varchar, col2 int);
create table currency ( id number, short_desc varchar, long_desc varchar);

--Original Table Schema

CREATE TABLE SIGNUP (SIGNUP_ID VARCHAR2(20) PRIMARY KEY NOT NULL, PASSWORD VARCHAR2(15) NOT NULL);

CREATE TABLE USER (USER_ID NUMBER(10) PRIMARY KEY NOT NULL, SIGNUP_ID VARCHAR2 , FOREIGN KEY (SIGNUP_ID) REFERENCES SIGNUP(SIGNUP_ID)
, USER_CREATE_TIMESTAMP TIMESTAMP, USER_DELETE_TIMESTAMP TIMESTAMP, USER_DELETED_FLAG VARCHAR2(1) CONSTRAINT FLAG_CHK CHECK (USER_DELETED_FLAG IN ('Y','N')));

CREATE TABLE USER_DTL (UD_ID NUMBER(10) PRIMARY KEY NOT NULL, USER_ID NUMBER, FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID), NAME VARCHAR2(30), USER_MAIL_ID VARCHAR2(30), USER_MOBILE NUMBER(15), USER_COUNTRY  VARCHAR2(30), USER_CURRENCY VARCHAR2(30));

CREATE TABLE GROUPS(GROUP_ID NUMBER(10) PRIMARY KEY NOT NULL, GROUP_NAME VARCHAR2(50), GRP_CURRENCY VARCHAR2(10), 
GRP_CREATE_TIMESTAMP TIMESTAMP, GRP_DELETE_TIMESTAMP TIMESTAMP, GRP_DELETED_FLAG VARCHAR2(1) CONSTRAINT FLAG_CHK CHECK (GRP_DELETED_FLAG IN ('Y','N')));

CREATE TABLE USER_GROUP(UG_ID NUMBER(10) PRIMARY KEY NOT NULL,GROUP_ID NUMBER, FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID), USER_ID NUMBER, FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
USER_ENTRY_TIMESTAMP TIMESTAMP, USER_DELETION_TIMESTAMP TIMESTAMP, USER_ACTIVE VARCHAR2(1) CONSTRAINT USER_ACTIVE_CHK CHECK (USER_ACTIVE IN ('Y','N')));

CREATE TABLE TRANSACTION(TXN_ID NUMBER(15) PRIMARY KEY NOT NULL, PAID_BY NUMBER, FOREIGN KEY(PAID_BY) REFERENCES USER(USER_ID), GROUP_ID NUMBER, FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID),
SHARE_TYPE VARCHAR2(30), TXN_CREATE_TIMESTAMP TIMESTAMP, TXN_DELETE_TIMESTAMP TIMESTAMP);

CREATE TABLE SPLIT(SPLIT_ID NUMBER(15), TXN_ID NUMBER, FOREIGN KEY(TXN_ID) REFERENCES TRANSACTION(TXN_ID), TXN_TOTAL_AMT NUMBER(15), SPLIT_USER_ID NUMBER, FOREIGN KEY(SPLIT_USER_ID) REFERENCES USER(USER_ID),
SHARE_AMOUNT NUMBER(15), CREDIT VARCHAR2(1) CONSTRAINT CREDIT_CHK CHECK (CREDIT IN ('Y','N')), SPLIT_ACTIVE VARCHAR2(1) CONSTRAINT SPLIT_ACTIVE_CHK CHECK (SPLIT_ACTIVE IN ('Y','N')), SPLIT_TIMESTAMP TIMESTAMP);